spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 1d4d564786335e43323b
            client-secret: 비밀키
            scope: name,email,avatar_url
          google:
            client-id: 410774630700-c8nhmnc4vebebk41eck18n80h5bjac9a.apps.googleusercontent.com
            client-secret: 비밀키
            scope: profile,email
          naver:
            client-id: 1A02Qa76U_uHB177O8Vv
            client-secret: 비밀키
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization_grant_type: authorization_code
            scope: name,email,profile_image
            client-name: Naver
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
