spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 1d4d564786335e43323b
            client-secret: 비밀키
            scope: name,email,avatar_url
          google:
            client-id: 410774630700-c8nhmnc4vebebk41eck18n80h5bjac9a.apps.googleusercontent.com
            client-secret: 비밀키
            scope: profile,email
